// Generated by NkSL Shader Compiler
// Target: HLSL SM50

float2 nksl_texsize2d(Texture2D t) { uint w,h; t.GetDimensions(w,h); return float2(w,h); }
column_major float3x3 nksl_inverse(column_major float3x3 m) {
    float a=m[0][0],b=m[0][1],c=m[0][2],d=m[1][0],e=m[1][1],f=m[1][2],g=m[2][0],h=m[2][1],k=m[2][2];
    float det = a*(e*k-f*h) - b*(d*k-f*g) + c*(d*h-e*g);
    float inv = 1.0f/det;
    column_major float3x3 r;
    r[0]=float3( (e*k-f*h)*inv, -(b*k-c*h)*inv,  (b*f-c*e)*inv );
    r[1]=float3(-(d*k-f*g)*inv,  (a*k-c*g)*inv, -(a*f-c*d)*inv );
    r[2]=float3( (d*h-e*g)*inv, -(a*h-b*g)*inv,  (a*e-b*d)*inv );
    return r;
}

cbuffer MainUBO : register(b0)
{
    column_major float4x4 model;
    column_major float4x4 view;
    column_major float4x4 proj;
    column_major float4x4 lightVP;
    float4 lightDirW;
    float4 eyePosW;
    float ndcZScale;
    float ndcZOffset;
    float _pad0;
    float _pad1;
};

struct VS_Input
{
    float3 apos : POSITION;
    float3 anormal : NORMAL;
    float4 acolor : TEXCOORD2;
    float2 auv : TEXCOORD3;
    uint _VertexID   : SV_VertexID;
    uint _InstanceID : SV_InstanceID;
};

struct VS_Output
{
    float4 _Position : SV_Position;
    float3 vworldpos : TEXCOORD0;
    float3 vnormal : NORMAL;
    float4 vcolor : TEXCOORD2;
    float4 vshadowcoord : TEXCOORD3;
    float2 vuv : TEXCOORD4;
};

VS_Output main(VS_Input input)
{
    VS_Output output;
    float4 worldpos = mul(model, float4(input.apos, 1.0f));
    output.vworldpos = worldpos.xyz;
    column_major float3x3 normalmat = transpose(nksl_inverse((float3x3)(model)));
    output.vnormal = normalize(mul(normalmat, input.anormal));
    output.vcolor = input.acolor;
    output.vshadowcoord = mul(lightVP, worldpos);
    output.vuv = input.auv;
    output._Position = mul(mul(proj, view), worldpos);
    return output;
}

// Generated by NkSL Shader Compiler
// Target: HLSL SM50

float2 nksl_texsize2d(Texture2D t) { uint w,h; t.GetDimensions(w,h); return float2(w,h); }
column_major float3x3 nksl_inverse(column_major float3x3 m) {
    float a=m[0][0],b=m[0][1],c=m[0][2],d=m[1][0],e=m[1][1],f=m[1][2],g=m[2][0],h=m[2][1],k=m[2][2];
    float det = a*(e*k-f*h) - b*(d*k-f*g) + c*(d*h-e*g);
    float inv = 1.0f/det;
    column_major float3x3 r;
    r[0]=float3( (e*k-f*h)*inv, -(b*k-c*h)*inv,  (b*f-c*e)*inv );
    r[1]=float3(-(d*k-f*g)*inv,  (a*k-c*g)*inv, -(a*f-c*d)*inv );
    r[2]=float3( (d*h-e*g)*inv, -(a*h-b*g)*inv,  (a*e-b*d)*inv );
    return r;
}

cbuffer MainUBO : register(b0)
{
    column_major float4x4 model;
    column_major float4x4 view;
    column_major float4x4 proj;
    column_major float4x4 lightVP;
    float4 lightDirW;
    float4 eyePosW;
    float ndcZScale;
    float ndcZOffset;
    float _pad0;
    float _pad1;
};

Texture2D ushadowmap_tex : register(t1);
SamplerComparisonState ushadowmap_smp : register(s1);
Texture2D ualbedomap_tex : register(t2);
SamplerState ualbedomap_smp : register(s2);

struct PS_Input
{
    float4 _Position : SV_Position;
    float3 vworldpos : TEXCOORD0;
    float3 vnormal : NORMAL;
    float4 vcolor : TEXCOORD2;
    float4 vshadowcoord : TEXCOORD3;
    float2 vuv : TEXCOORD4;
};

struct PS_Output
{
    float4 fragcolor : SV_Target0;
};

PS_Output main(PS_Input input)
{
    PS_Output output;
    float3 n = normalize(input.vnormal);
    float3 l = normalize(-lightDirW.xyz);
    float3 v = normalize((eyePosW.xyz - input.vworldpos));
    float3 h = normalize((l + v));
    float3 proj = (input.vshadowcoord.xyz / input.vshadowcoord.w);
    float su = ((proj.x * 0.5f) + 0.5f);
    float sv = ((proj.y * 0.5f) + 0.5f);
    float sz = ((proj.z * ndcZScale) + ndcZOffset);
    float cosa = max(dot(n, l), 0.0f);
    float bias = lerp(0.005f, 0.0005f, cosa);
    sz -= bias;
    float shadow = 1.0f;
    if ((((((su >= 0.0f) && (su <= 1.0f)) && (sv >= 0.0f)) && (sv <= 1.0f)) && (sz <= 1.0f)))
    {
        float2 texelsize = (1.0f / (float2)(nksl_texsize2d(ushadowmap_tex)));
        shadow = 0.0f;
        for (int x = -1; (x <= 1); ++x)
        {
            for (int y = -1; (y <= 1); ++y)
            {
                float ox = (float(x) * texelsize.x);
                float oy = (float(y) * texelsize.y);
                shadow += ushadowmap_tex.SampleCmpLevelZero(ushadowmap_smp, float2((su + ox), (sv + oy)), sz);
            }
        }
        shadow /= 9.0f;
    }
    shadow = max(shadow, 0.35f);
    float3 basecolor = input.vcolor.rgb;
    if ((input.vcolor.w > 0.5f))
    {
        basecolor = ualbedomap_tex.Sample(ualbedomap_smp, (input.vuv / 3.0f)).rgb;
    }
    float diff = max(dot(n, l), 0.0f);
    float spec = pow(max(dot(n, h), 0.0f), 32.0f);
    float3 ambient = (0.15f * basecolor);
    float3 diffuse = ((shadow * diff) * basecolor);
    float3 specular = ((shadow * spec) * (float3)(0.4f));
    output.fragcolor = float4(((ambient + diffuse) + specular), 1.0f);
    return output;
}


// Generated by NkSL Shader Compiler
// Target: HLSL SM50

float2 nksl_texsize2d(Texture2D t) { uint w,h; t.GetDimensions(w,h); return float2(w,h); }
column_major float3x3 nksl_inverse(column_major float3x3 m) {
    float a=m[0][0],b=m[0][1],c=m[0][2],d=m[1][0],e=m[1][1],f=m[1][2],g=m[2][0],h=m[2][1],k=m[2][2];
    float det = a*(e*k-f*h) - b*(d*k-f*g) + c*(d*h-e*g);
    float inv = 1.0f/det;
    column_major float3x3 r;
    r[0]=float3( (e*k-f*h)*inv, -(b*k-c*h)*inv,  (b*f-c*e)*inv );
    r[1]=float3(-(d*k-f*g)*inv,  (a*k-c*g)*inv, -(a*f-c*d)*inv );
    r[2]=float3( (d*h-e*g)*inv, -(a*h-b*g)*inv,  (a*e-b*d)*inv );
    return r;
}

cbuffer ShadowUBO : register(b0)
{
    column_major float4x4 model;
    column_major float4x4 view;
    column_major float4x4 proj;
    column_major float4x4 lightVP;
    float4 lightDirW;
    float4 eyePosW;
    float ndcZScale;
    float ndcZOffset;
    float _pad0;
    float _pad1;
};

struct VS_Input
{
    float3 apos : POSITION;
    uint _VertexID   : SV_VertexID;
    uint _InstanceID : SV_InstanceID;
};

struct VS_Output
{
    float4 _Position : SV_Position;
};

VS_Output main(VS_Input input)
{
    VS_Output output;
    output._Position = mul(mul(lightVP, model), float4(input.apos, 1.0f));
    return output;
}

// Generated by NkSL Shader Compiler
// Target: HLSL SM50

float2 nksl_texsize2d(Texture2D t) { uint w,h; t.GetDimensions(w,h); return float2(w,h); }
column_major float3x3 nksl_inverse(column_major float3x3 m) {
    float a=m[0][0],b=m[0][1],c=m[0][2],d=m[1][0],e=m[1][1],f=m[1][2],g=m[2][0],h=m[2][1],k=m[2][2];
    float det = a*(e*k-f*h) - b*(d*k-f*g) + c*(d*h-e*g);
    float inv = 1.0f/det;
    column_major float3x3 r;
    r[0]=float3( (e*k-f*h)*inv, -(b*k-c*h)*inv,  (b*f-c*e)*inv );
    r[1]=float3(-(d*k-f*g)*inv,  (a*k-c*g)*inv, -(a*f-c*d)*inv );
    r[2]=float3( (d*h-e*g)*inv, -(a*h-b*g)*inv,  (a*e-b*d)*inv );
    return r;
}

void main()
{
}

// Generated by NkSL Shader Compiler
// Target: HLSL SM50

float2 nksl_texsize2d(Texture2D t) { uint w,h; t.GetDimensions(w,h); return float2(w,h); }
column_major float3x3 nksl_inverse(column_major float3x3 m) {
    float a=m[0][0],b=m[0][1],c=m[0][2],d=m[1][0],e=m[1][1],f=m[1][2],g=m[2][0],h=m[2][1],k=m[2][2];
    float det = a*(e*k-f*h) - b*(d*k-f*g) + c*(d*h-e*g);
    float inv = 1.0f/det;
    column_major float3x3 r;
    r[0]=float3( (e*k-f*h)*inv, -(b*k-c*h)*inv,  (b*f-c*e)*inv );
    r[1]=float3(-(d*k-f*g)*inv,  (a*k-c*g)*inv, -(a*f-c*d)*inv );
    r[2]=float3( (d*h-e*g)*inv, -(a*h-b*g)*inv,  (a*e-b*d)*inv );
    return r;
}

cbuffer TextUBO : register(b0)
{
    column_major float4x4 mvp;
    float4 color;
};

struct VS_Input
{
    float2 apos : POSITION;
    float2 auv : TEXCOORD1;
    uint _VertexID   : SV_VertexID;
    uint _InstanceID : SV_InstanceID;
};

struct VS_Output
{
    float4 _Position : SV_Position;
    float2 vuv : TEXCOORD0;
};

VS_Output main(VS_Input input)
{
    VS_Output output;
    output.vuv = input.auv;
    output._Position = mul(mvp, float4(input.apos, 0.0f, 1.0f));
    return output;
}


// Generated by NkSL Shader Compiler
// Target: HLSL SM50

float2 nksl_texsize2d(Texture2D t) { uint w,h; t.GetDimensions(w,h); return float2(w,h); }
column_major float3x3 nksl_inverse(column_major float3x3 m) {
    float a=m[0][0],b=m[0][1],c=m[0][2],d=m[1][0],e=m[1][1],f=m[1][2],g=m[2][0],h=m[2][1],k=m[2][2];
    float det = a*(e*k-f*h) - b*(d*k-f*g) + c*(d*h-e*g);
    float inv = 1.0f/det;
    column_major float3x3 r;
    r[0]=float3( (e*k-f*h)*inv, -(b*k-c*h)*inv,  (b*f-c*e)*inv );
    r[1]=float3(-(d*k-f*g)*inv,  (a*k-c*g)*inv, -(a*f-c*d)*inv );
    r[2]=float3( (d*h-e*g)*inv, -(a*h-b*g)*inv,  (a*e-b*d)*inv );
    return r;
}

cbuffer TextUBO : register(b0)
{
    column_major float4x4 mvp;
    float4 color;
};

Texture2D utext_tex : register(t1);
SamplerState utext_smp : register(s1);

struct PS_Input
{
    float4 _Position : SV_Position;
    float2 vuv : TEXCOORD0;
};

struct PS_Output
{
    float4 outcolor : SV_Target0;
};

PS_Output main(PS_Input input)
{
    PS_Output output;
    float a = utext_tex.Sample(utext_smp, input.vuv).r;
    output.outcolor = float4(color.rgb, (color.a * a));
    return output;
}